Description: A template for creation of a single EC2 instance

Parameters:
  EC2InstanceType:
    Description: EC instance type configuration
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium

  EC2InstanceAmiID:
    Description: AMI identifier of the image to deploy for the EC2 instance
    Type: String
    Default: ami-08e2d37b6a0129927

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref EC2InstanceAmiID
      InstanceType: !Ref EC2InstanceType

Outputs:
  PublicIp:
    Description: public IP of the created EC2 instance
    Value: !GetAtt EC2Instance.PublicIp