Description: Single EC2 instance stack for AWS course week_0 assignment

Parameters:
  EC2InstanceType:
    Description: EC2 instance type configuration
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium

  EC2InstanceAmiID:
    Description: AMI identifier of the image to deploy for the EC2 instance
    Type: String
    Default: ami-08e2d37b6a0129927

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref EC2InstanceAmiID
      InstanceType: !Ref EC2InstanceType

Outputs:
  PublicIp:
    Description: EC2 instance public IP
    Value: !GetAtt EC2Instance.PublicIp
  PublicDnsName:
    Description: EC2 instance public DNS name
    Value: !GetAtt EC2Instance.PublicDnsName