Description: EC2 instances stack with assigned security policies and auto scaling groups and preinstalled Java 8 for AWS course week_1 assignment

Parameters:
  EC2InstanceType:
    Description: EC2 instance type configuration
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium

  EC2InstanceAmiID:
    Description: AMI identifier of the image to deploy for the EC2 instance
    Type: String
    Default: ami-08e2d37b6a0129927

  KeyName:
    Description: EC2 instance SSH key
    Type: AWS::EC2::KeyPair::KeyName
    Default: svoitenko-key-pair

  MaxSizeASG:
    Description: Max Size for the ASG
    Type: String
    Default: 3
  MinSizeASG:
    Description: Min Size for the ASG
    Type: String
    Default: 2
  DesiredCapacityASG:
    Description: Desired capacity for the ASG
    Type: String
    Default: 2


Resources:
  LaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      KeyName: !Ref KeyName
      ImageId: !Ref EC2InstanceAmiID
      InstanceType: !Ref EC2InstanceType
      SecurityGroups:
        - !Ref SSHSecurityGroup
        - !Ref HTTPSecurityGroup
      UserData:
        Fn::Base64:
          !Sub |
          #!/bin/bash
          yum update -y
          yum install java-1.8.0-openjdk -y

  SSHSecurityGroup:
    Description: Security group to allow inbound SSH connection
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  HTTPSecurityGroup:
    Description: Security group to allow inbound HTTP connection
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable HTTP access via port 80
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: SVoitenkoAutoscalingGroup
      Cooldown: 60
      DesiredCapacity:
        Ref: DesiredCapacityASG
      LaunchConfigurationName:
        Ref: LaunchConfig
      MaxSize:
        Ref: MaxSizeASG
      MinSize:
        Ref: MinSizeASG
      AvailabilityZones:
        - us-west-2a
        - us-west-2b
        - us-west-2c
        - us-west-2d


Outputs:
  AutoscalingGroup:
    Description: "The newly created ASG"
    Value:
      Ref: "AutoScalingGroup"
  LaunchConfig:
    Description: "The newly created launch config"
    Value:
      Ref: "LaunchConfig"